PageTurn/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('homepage.urls')),
    path('laporan_buku_rusak/', include('laporan_buku_rusak.urls')),
    path('admin/', admin.site.urls),
    path('katalog/', include('katalog.urls')),
    path('peminjaman/', include('peminjaman.urls')),
    path('review/', include('review.urls')),
    path('request_buku/', include('request_buku.urls')),
    path('auth/', include('authentication.urls')),
]

peminjaman/urls.py
from django.contrib import admin
from django.urls import include, path

from peminjaman.views import *

app_name = 'peminjaman'

urlpatterns = [
    path("", show_peminjaman, name="show_peminjaman"),
    path('new/', add_peminjaman, name='add_peminjaman'),
    path('history/', show_history, name='show_history'),
    path('get-item/', get_item_json, name='get_item_json'),
    path('get-item-returned/', get_item_json_returned, name='get_item_json_returned'),
    path('get-book/', get_book_json, name='get_book_json'),
    path('return-book/<int:id>/', return_book, name='return_book'),
    path('add-book/<int:id>/', add_book, name='add_book'),
    path('get-selected/', get_selected_books, name='get_selected_books'),
    path('get-items/', get_items_filter, name='get_items_filter'),
    path('return-book-flutter/<int:id>/', return_book_flutter, name='return_book_flutter'),
    path('get-history/', get_history, name='get_history'),
]

review/urls.py
from django.urls import path

from review.views import (add_review_ajax, create_product_flutter,
                          create_review, delete_review, edit_review,
                          get_review_json, show_json, show_main)

app_name = 'review_buku'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-review', create_review, name='create_review'),
    path('edit-review/<int:id>', edit_review, name='edit_review'),
    path('delete/<int:id>', delete_review, name='delete_review'), # sesuaikan dengan nama fungsi yang dibuat
    path('get-review/', get_review_json, name='get_review_json'),
    path('create-product-ajax/', add_review_ajax, name='add_review_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
    path('json/', show_json, name='show_json'),
]

peminjaman/models.py
from django.db import models

from katalog.models import Book
from PageTurn import settings


# Create your models here.
class Peminjaman(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    tgl_dipinjam = models.DateField(null=True)
    durasi_peminjaman = models.IntegerField(null=True)
    tgl_batas = models.DateField(null=True)
    tgl_dikembalikan = models.DateField(null=True)
    is_returned = models.BooleanField(default=False)

peminjaman/forms.py
from django import forms

from .models import Peminjaman


class PeminjamanForm(forms.ModelForm):
    durasi_peminjaman = forms.IntegerField(label='Durasi Peminjaman (dalam hari)', min_value=1, max_value=14)

    class Meta:
        model = Peminjaman
        fields = ['durasi_peminjaman']

peminjaman/views.py
import json
from datetime import datetime, timedelta

from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.http import HttpResponse, HttpResponseNotFound, JsonResponse
from django.shortcuts import redirect, render
from django.views.decorators.csrf import csrf_exempt

from katalog.models import Book
from peminjaman.forms import PeminjamanForm
from peminjaman.models import Peminjaman


def show_peminjaman(request):
    if request.user.is_authenticated:
        books = Book.objects.all()
        dipinjam = Peminjaman.objects.filter(user = request.user, is_returned = False)
        dikembalikan = Peminjaman.objects.filter(user = request.user, is_returned = True)
        genres = set()
        for book in Book.objects.all():
            genres.add(book.genre)
        context = {
            'user' : request.user,
            'books' : books,
            'dipinjam' : dipinjam,
            'dikembalikan' : dikembalikan,
            'genres' : genres,
            'last_login' : request.COOKIES["last_login"][:-10] if "last_login" in request.COOKIES else "",
        }

        return render(request, 'peminjaman.html', context)
    else:
        books = Book.objects.filter()
        genres = set()
        for book in Book.objects.all():
            genres.add(book.genre)
        context = {
            'books' : books,
            'genres' : genres,
        }
        return render(request, 'guest_peminjaman.html', context)

@login_required(login_url='/peminjaman')
def add_peminjaman(request):
    books = Book.objects.filter(is_dipinjam = False)
    kosong = Book.objects.filter(is_dipinjam = True)
    genres = set()
    for book in Book.objects.all():
        genres.add(book.genre)
    context = {
        'books' : books,
        'genres' : genres,
        'kosong' : kosong,
        'form': PeminjamanForm(),
        'last_login' : request.COOKIES["last_login"][:-10] if "last_login" in request.COOKIES else "",
    }
    return render(request, 'add_peminjaman.html', context)

@login_required(login_url='/peminjaman')
def show_history(request):
    books = Book.objects.all()
    dikembalikan = Peminjaman.objects.filter(user = request.user, is_returned = True)
    genres = set()
    for book in Book.objects.all():
        genres.add(book.genre)
    context = {
        'user' : request.user,
        'books' : books,
        'dikembalikan' : dikembalikan,
        'genres' : genres,
        'last_login' : request.COOKIES["last_login"][:-10] if "last_login" in request.COOKIES else "",
    }

    return render(request, 'history_peminjaman.html', context)


def get_item_json(request):
    item = Peminjaman.objects.filter(user=request.user, is_returned = False)
    return HttpResponse(serializers.serialize('json', item))

def get_item_json_returned(request):
    item = Peminjaman.objects.filter(user=request.user, is_returned = True)
    return HttpResponse(serializers.serialize('json', item))

def get_book_json(request):
    item = Book.objects.all()
    return HttpResponse(serializers.serialize('json', item))

@csrf_exempt
def return_book(request, id):
    if request.method == 'POST':
        item = Peminjaman.objects.get(pk=id)
        item.is_returned = True
        item.tgl_dikembalikan = datetime.now().date()
        item.save()
        buku = item.book
        buku.is_dipinjam = False
        buku.cnt_dipinjam += 1
        buku.save()
        return HttpResponse(b"RETURNED", status=201)
    return HttpResponseNotFound()

@csrf_exempt
def add_book(request, id):
    if request.method == 'POST':
        form = PeminjamanForm(request.POST)
        if form.is_valid():
            buku = Book.objects.get(pk=id)
            new_item = Peminjaman.objects.create(
                user=request.user,
                book=buku,
                tgl_dipinjam=datetime.now().date(),
                durasi_peminjaman=form.cleaned_data['durasi_peminjaman'],
                tgl_batas=datetime.now().date() + timedelta(days=form.cleaned_data['durasi_peminjaman']),
                is_returned=False
            )
            new_item.save()
            buku.is_dipinjam = True
            buku.save()
            return HttpResponse(b"CREATED", status=201)
    return HttpResponseNotFound()

@csrf_exempt
def get_selected_books(request):
    selected_books = request.POST.getlist('booklist')[0]
    durasi = request.POST.getlist('durasi')[0]
    try:
        durasi = int(durasi)
        if durasi > 14 or durasi < 1:
            raise Exception()
    except:
        return JsonResponse({
                "status": False,
                "message": "Durasi hanya dapat berupa angka antara 1-14!"
            }, status=400)
    
    selected_books = json.loads(selected_books)
    if selected_books:
        for id in selected_books:
            buku = Book.objects.get(pk=id)
            new_item = Peminjaman.objects.create(
                user=request.user,
                book=buku,
                tgl_dipinjam=datetime.now().date(),
                durasi_peminjaman=durasi,
                tgl_batas=datetime.now().date() + timedelta(days=durasi),
                is_returned=False
            )
            new_item.save()
            buku.is_dipinjam = True
            buku.save()
        return JsonResponse({
            "status": True,
            "message": "Berhasil meminjam buku!"
        }, status=201)
    else:
        return JsonResponse({
                "status": False,
                "message": "Terdapat Error!"
            }, status=400)

@csrf_exempt
def return_book_flutter(request, id):
    if request.method == 'POST':
        item = Peminjaman.objects.get(pk=id)
        item.is_returned = True
        item.tgl_dikembalikan = datetime.now().date()
        item.save()
        buku = item.book
        buku.is_dipinjam = False
        buku.cnt_dipinjam += 1
        buku.save()
        if item.tgl_dikembalikan > item.tgl_batas:
            return JsonResponse({
                    "status": True,
                    "message": "Lain kali jangan telat ya mengembalikan bukunya!"
                }, status=201)
        else:
            return JsonResponse({
                    "status": True,
                    "message": "Terima kasih telah mengembalikan buku ini tepat waktu!"
                }, status=201)
    return JsonResponse({
                    "status": False,
                    "message": "Error!"
                }, status=400)


def get_items_filter(request):
    search_query = request.GET.get('search', '')
    genres = request.GET.getlist('genres')
    peminjamans = Peminjaman.objects.filter(user = request.user)
    item_ret = []
    
    for item in peminjamans:
        if item.is_returned:
            continue
        book = item.book
        if search_query.lower() in book.name.lower() or search_query.lower() in book.author.lower():
            if genres:
                if book.genre in genres:
                    item_ret.append(item)
            else:
                item_ret.append(item)
    
    # Serialisasi data buku ke JSON
    return HttpResponse(serializers.serialize('json', item_ret))

def get_history(request):
    search_query = request.GET.get('search', '')
    genres = request.GET.getlist('genres')
    peminjamans = Peminjaman.objects.filter(user = request.user)
    item_ret = []
    
    for item in peminjamans:
        if not item.is_returned:
            continue
        book = item.book
        if search_query.lower() in book.name.lower() or search_query.lower() in book.author.lower():
            if genres:
                if book.genre in genres:
                    item_ret.append(item)
            else:
                item_ret.append(item)
    
    # Serialisasi data buku ke JSON
    return HttpResponse(serializers.serialize('json', item_ret))

peminjaman/templates/add_peminjaman.html
{% extends "base.html" %}
{% load static %}
{% block meta %}
    <title>Peminjaman Buku</title>
    <link rel="stylesheet" href="{% static 'css/add_peminjaman.css' %}?{% now "U" %}">
{% endblock meta %}

{% block content %}
<div class="container">
    <h1 class="display-4 fw-bold text-center">Selamat datang, {{ user.username }}!</h1>
    <h5 class="mt-2 mb-3 text-center">Berikut adalah daftar buku, klik gambar buku untuk meminjamnya, warna merah artinya tidak tersedia. </h5>
    <div class="container w-75">
        <form class="d-flex rounded border">
            <input class="form-control" type="text" placeholder="Search Books and Authors" aria-label="Search" id="search-book">
        </form>
    </div>
    <div class="row">
        <h4 class="card-title mb-3">Filter Buku</h4>
        <div class="col-md-2">
            <div class="card">
                <div class="card-body">
                    <form id="filterForm">
                        <h5 class="card-title mb-3">Genre</h5>
                        {% for genre in genres %}
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" value="{{ genre }}" name="genre" id="{{ genre }}" checked>
                            <label class="form-check-label" for="{{ genre }}">{{ genre }}</label>
                        </div>
                        {% endfor %}
                        <h5 class="card-title mb-3 mt-3">Status</h5>
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" value=0 id="Ready" name="isReady" checked>
                            <label class="form-check-label" for="Ready">Ready</label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" value=1 id="Not-Ready" name="isReady" checked>
                            <label class="form-check-label" for="Not Ready">Not Ready</label>
                        </div>
                    </form>
                </div>
            </div>
            <div class="d-flex justify-content-start align-items-start mt-3">
                <a href="{% url 'peminjaman:show_peminjaman' %}" class="btn" style="color: #be6933;"><strong>Back</strong></a>
            </div>
            <div class="d-flex justify-content-start align-items-start mt-3">
                <h4>Last Login: <br> {{last_login}}</h4>
            </div>
        </div>

        <!-- Daftar Buku -->
        <div class="col-md-10">
            <div id="book-card" class="row row-cols-1 row-cols-md-4 g-4"></div>
        </div>
    </div>
</div>
{% for book in books %}
<div class="modal fade" id="pinjamModal{{ book.pk }}" tabindex="-1" aria-labelledby="pinjamModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="pinjamModal">{{ book.name }}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6">
                        <!-- Gambar Buku -->
                        <img src="{{ book.image }}" alt="{{ book.name }} Cover" style="width: 100%;">
                    </div>
                    <div class="col-md-6">
                        <!-- Detail Buku -->
                        <p><strong>Penulis:</strong> {{ book.author }}</p>
                        <p><strong>Genre:</strong> {{ book.genre }}</p>
                        <p><strong>Tahun:</strong> {{ book.year }}</p>
                        <p><strong>Deskripsi:</strong> {{ book.description | truncatechars:250 }}</p>
                    </div>
                </div>
                <form id="pinjamForm" onsubmit="return false;" >
                    {% csrf_token %}
                    <div class="form-group">
                        <strong>{{ form.durasi_peminjaman.label_tag }}</strong>
                        {{ form.durasi_peminjaman }}
                    </div>
            </div>
            <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" name="add_button" data-id="{{ book.id }}" class="btn btn-primary align-content-lg-center">Pinjam Buku</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% for book in kosong %}
<div class="modal fade" id="kosongModal{{ book.pk }}" tabindex="-1" aria-labelledby="kosongModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="kosongModal"><strong>Maaf, buku ini sedang dipinjam!</strong><br>{{ book.name }}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6">
                        <!-- Gambar Buku -->
                        <img src="{{ book.image }}" alt="{{ book.name }} Cover" style="width: 100%;">
                    </div>
                    <div class="col-md-6">
                        <!-- Detail Buku -->
                        <p><strong>Penulis:</strong> {{ book.author }}</p>
                        <p><strong>Genre:</strong> {{ book.genre }}</p>
                        <p><strong>Tahun:</strong> {{ book.year }}</p>
                        <p><strong>Deskripsi:</strong> {{ book.description | truncatechars:250 }}</p>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
{% endfor %}
<div id="url-get-book" data-url="{% url 'peminjaman:get_book_json' %}"></div>
<div id="url-add-book" data-url="{% url 'peminjaman:add_book' '0' %}"></div>
<div id="url-back" data-url="{% url 'peminjaman:show_peminjaman' %}"></div>

<script src="{% static 'js/add_peminjaman.js' %}?{% now "U" %}"></script>

{% endblock content %}

peminjaman/templates/guest_peminjaman.html
{% extends "base.html" %}
{% load static %}
{% block meta %}
    <title>Peminjaman Buku</title>
    <link rel="stylesheet" href="{% static 'css/guest_peminjaman.css' %}?{% now "U" %}">
{% endblock meta %}

{% block content %}
<div class="container">
    <h1 class="display-4 fw-bold text-center">Selamat datang, Guest!</h1>
    <h5 class="mt-1 mb-3 text-center">Berikut adalah daftar buku, klik gambar buku untuk melihat infonya, warna merah artinya tidak tersedia. </h5>
    <h5 class="mt-2 mb-3 text-center">
        Login <a href="/login">di sini</a> terlebih dahulu untuk meminjam buku!
    </h5>
    <div class="container w-75">
        <form class="d-flex rounded border">
            <input class="form-control" type="text" placeholder="Search Books and Authors" aria-label="Search" id="search-book">
        </form>
    </div>
    <div class="row">
        <h4 class="card-title mb-3">Filter Buku</h4>
        <div class="col-md-2">
            <div class="card">
                <div class="card-body">
                    <form id="filterForm">
                        <h5 class="card-title mb-3">Genre</h5>
                        {% for genre in genres %}
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" value="{{ genre }}" name="genre" id="{{ genre }}" checked>
                            <label class="form-check-label" for="{{ genre }}">{{ genre }}</label>
                        </div>
                        {% endfor %}
                        <h5 class="card-title mb-3 mt-3">Status</h5>
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" value=0 id="Ready" name="isReady" checked>
                            <label class="form-check-label" for="Ready">Ready</label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" value=1 id="Not-Ready" name="isReady" checked>
                            <label class="form-check-label" for="Not Ready">Not Ready</label>
                        </div>
                    </form>
                </div>
            </div>
            <!-- <div class="d-flex justify-content-start align-items-start mt-3">
                <a href="{% url 'peminjaman:show_peminjaman' %}" class="btn" style="color: #be6933;"><strong>Back</strong></a>
            </div> -->
        </div>

        <!-- Daftar Buku -->
        <div class="col-md-10">
            <div id="book-card" class="row row-cols-1 row-cols-md-4 g-4"></div>
        </div>
    </div>
</div>
{% for book in books %}
<div class="modal fade" id="kosongModal{{ book.pk }}" tabindex="-1" aria-labelledby="kosongModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="kosongModal"><strong>{{ book.name }}</strong></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6">
                        <!-- Gambar Buku -->
                        <img src="{{ book.image }}" alt="{{ book.name }} Cover" style="width: 100%;">
                    </div>
                    <div class="col-md-6">
                        <!-- Detail Buku -->
                        <p><strong>Penulis:</strong> {{ book.author }}</p>
                        <p><strong>Genre:</strong> {{ book.genre }}</p>
                        <p><strong>Tahun:</strong> {{ book.year }}</p>
                        <p><strong>Deskripsi:</strong> {{ book.description | truncatechars:250 }}</p>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
{% endfor %}
<div id="url-get-book" data-url="{% url 'peminjaman:get_book_json' %}"></div>
<div id="url-add-book" data-url="{% url 'peminjaman:add_book' '0' %}"></div>
<div id="url-back" data-url="{% url 'peminjaman:show_peminjaman' %}"></div>

<script src="{% static 'js/guest_peminjaman.js' %}?{% now "U" %}"></script>

{% endblock content %}

peminjaman/templates/history_peminjaman.html
{% extends "base.html" %}
{% load static %}
{% block meta %}
    <title>Peminjaman Buku</title>
    <link rel="stylesheet" href="{% static 'css/history_peminjaman.css' %}?{% now "U" %}">
{% endblock meta %}

{% block content %}
<div class="container">
    <div class="text-center">
        <h1 class="display-4 fw-bold text-center">Selamat datang, {{ user.username }}!</h1>
        <h5 class="mt-2 mb-3 text-center">Berikut ini adalah history dari buku yang pernah kamu pinjam sebelumnya. </h5>
    </div>
    
    <div class="container w-75">
        <form class="d-flex rounded border">
            <input class="form-control" type="text" placeholder="Search Books and Authors" aria-label="Search" id="search-book">
        </form>
    </div>
    <!-- <div class="row" id="item_card"> </div> -->
    <div class="row">
        <!-- Filter Buku -->
        <h4 class="card-title mb-3">Filter Buku</h4>
        <div class="col-md-2">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title mb-3">Genre</h5>
                    <form id="filterForm">
                        {% for genre in genres %}
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" value="{{ genre }}" id="{{ genre }}" checked>
                            <label class="form-check-label" for="{{ genre }}">{{ genre }}</label>
                        </div>
                        {% endfor %}
                    </form>
                </div>
            </div>
            <div class="d-flex justify-content-start align-items-start mt-3">
                <a href="{% url 'peminjaman:show_peminjaman' %}" class="btn btn-primary mt-3">Back</a>
            </div>
            <div class="d-flex justify-content-start align-items-start mt-3">
                <h4>Last Login: <br> {{last_login}}</h4>
            </div>
        </div>
        <!-- Daftar Buku -->
        <div class="col-md-10">
            <div id="item-card" class="row row-cols-1 row-cols-md-2 g-4">
            </div>
        </div>
        
    </div>
</div>
{% for peminjaman in dikembalikan %}
<div class="modal fade" id="pinjamModal{{ peminjaman.pk }}" tabindex="-1" aria-labelledby="pinjamModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="pinjamModal">{{ peminjaman.book.name }}</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-4">
                        <!-- Gambar Buku -->
                        <img src="{{ peminjaman.book.image }}" alt="{{ book.name }} Cover" style="width: 100%;">
                    </div>
                    <div class="col-md-7">
                        <!-- Detail Buku -->
                        <div style="line-height: 4;">
                            <span><strong>Dipinjam oleh: </strong>{{ user.username }}</span>
                            <br>
                            <span><strong>Dipinjam tanggal: </strong>{{ peminjaman.tgl_dipinjam }}</span>
                            <br>
                            <span><strong>dikembalikan Pada: </strong>{{ peminjaman.tgl_dikembalikan}}</span>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
{% endfor %}
<div id="url-get-book" data-url="{% url 'peminjaman:get_book_json' %}"></div>
<div id="url-get-item" data-url="{% url 'peminjaman:get_item_json_returned' %}"></div>
<script src="{% static 'js/history_peminjaman.js' %}?{% now "U" %}"></script>
{% endblock content %}

peminjaman/templates/peminjaman.html
{% extends "base.html" %}
{% load static %}
{% block meta %}
    <title>Peminjaman Buku</title>
    <link rel="stylesheet" href="{% static 'css/peminjaman.css' %}?{% now "U" %}">
{% endblock meta %}

{% block content %}
<div class="container">
    <h1 class="display-4 fw-bold text-center">Selamat datang, {{ user.username }}!</h1>
    <h5 class="mt-2 mb-3 text-center">Berikut ini adalah buku yang sedang kamu pinjam, klik gambar buku untuk mengembalikannya. </h5>
    
    <div class="container w-75">
        <form class="d-flex rounded border">
            <input class="form-control" type="text" placeholder="Search Books and Authors" aria-label="Search" id="search-book">
        </form>
    </div>
    <!-- <div class="row" id="item_card"> </div> -->
    <div class="row">
        <!-- Filter Buku -->
        <h4 class="card-title mb-3">Filter Buku</h4>
        <div class="col-md-2">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title mb-3">Genre</h5>
                    <form id="filterForm">
                        {% for genre in genres %}
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" value="{{ genre }}" id="{{ genre }}" checked>
                            <label class="form-check-label" for="{{ genre }}">{{ genre }}</label>
                        </div>
                        {% endfor %}
                    </form>
                </div>
            </div>
            <div class="d-flex justify-content-start align-items-start mt-3">
                <a href="{% url 'peminjaman:add_peminjaman' %}" class="btn tes"><strong>Meminjam Buku?</strong></a>
            </div>
            <div class="d-flex justify-content-start align-items-start mt-3">
                <a href="{% url 'peminjaman:show_history' %}" class="btn"><strong>History Peminjaman</strong></a>
            </div>
            <div class="d-flex justify-content-start align-items-start mt-3">
                <h4>Last Login: <br> {{last_login}}</h4>
            </div>
        </div>
        <!-- Daftar Buku -->
        <div class="col-md-10">
            <div id="item-card" class="row row-cols-1 row-cols-md-4 g-4"></div>
        </div>
    </div>
</div>
{% for peminjaman in dipinjam %}
<div class="modal fade" id="pinjamModal{{ peminjaman.pk }}" tabindex="-1" aria-labelledby="pinjamModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="pinjamModal">{{ peminjaman.book.name }}</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-4">
                        <!-- Gambar Buku -->
                        <img src="{{ peminjaman.book.image }}" alt="{{ book.name }} Cover" style="width: 100%;">
                    </div>
                    <div class="col-md-7">
                        <!-- Detail Buku -->
                        <div style="line-height: 4;">
                            <span><strong>Dipinjam oleh: </strong>{{ user.username }}</span>
                            <br>
                            <span><strong>Dipinjam tanggal: </strong>{{ peminjaman.tgl_dipinjam }}</span>
                            <br>
                            <span><strong>Batas pengembalian: </strong>{{ peminjaman.tgl_batas }}</span>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" name="return_button" value={{peminjaman.pk}} data-bs-dismiss="modal">Kembalikan Buku</button>
            </div>
        </div>
    </div>
</div>
{% endfor %}
<div id="url-get-book" data-url="{% url 'peminjaman:get_book_json' %}"></div>
<div id="url-get-item" data-url="{% url 'peminjaman:get_item_json' %}"></div>
<div id="url-return-book" data-url="{% url 'peminjaman:return_book' '0' %}"></div>
<script src="{% static 'js/peminjaman.js' %}?{% now "U" %}"></script>
{% endblock content %}