PageTurn/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('homepage.urls')),
    path('laporan_buku_rusak/', include('laporan_buku_rusak.urls')),
    path('admin/', admin.site.urls),
    path('katalog/', include('katalog.urls')),
    path('peminjaman/', include('peminjaman.urls')),
    path('review/', include('review.urls')),
    path('request_buku/', include('request_buku.urls')),
    path('auth/', include('authentication.urls')),
]

review/urls.py
from django.urls import path

from review.views import (add_review_ajax, create_product_flutter,
                          create_review, delete_review, edit_review,
                          get_review_json, show_json, show_main)

app_name = 'review_buku'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-review', create_review, name='create_review'),
    path('edit-review/<int:id>', edit_review, name='edit_review'),
    path('delete/<int:id>', delete_review, name='delete_review'), # sesuaikan dengan nama fungsi yang dibuat
    path('get-review/', get_review_json, name='get_review_json'),
    path('create-product-ajax/', add_review_ajax, name='add_review_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
    path('json/', show_json, name='show_json'),
]

review/models.py
from django.db import models

from katalog.models import Book
from PageTurn import settings


class Product(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=255)
    date_added = models.DateField(auto_now_add=True)
    description = models.TextField()

# Create your models here.

review/forms.py
from django.forms import ModelForm

from review.models import Product


class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "description"]

review/views.py
import json

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.core import serializers
from django.http import (HttpResponse, HttpResponseNotFound,
                         HttpResponseRedirect, JsonResponse)
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from homepage.models import CustomUser
from review.forms import ProductForm
from review.models import Product


def show_main(request):
    reviews = Product.objects.all()
    context = {
        'review': reviews
    }

    return render(request, "reviewbuku.html", context)

def create_review(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        form.instance.user = request.user
        form.save()
        return HttpResponseRedirect(reverse('review_buku:show_main'))
        # review = form.save(commit=False)
        # review.user = request.user
        # review.save()
        # return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_review.html", context)

def edit_review(request, id):
    # Get review berdasarkan ID
    review = Product.objects.get(pk = id)

    # Set review sebagai instance dari form
    form = ProductForm(request.POST or None, instance=review)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('review_buku:show_main'))

    context = {'form': form}
    return render(request, "edit_review.html", context)

def delete_review(request, id):
    # Get data berdasarkan ID
    review = Product.objects.get(pk = id)
    # Hapus data
    review.delete()
    # Kembali ke halaman awal
    return HttpResponseRedirect(reverse('review_buku:show_main'))

def get_review_json(request):
    review_item = Product.objects.all()
    return HttpResponse(serializers.serialize('json', review_item))

def show_json(request):
    data = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@csrf_exempt
def add_review_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        description = request.POST.get("description")

        new_review = Product(user=request.user,name=name, description=description)
        new_review.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        # Handling AnonymousUser
        user = request.user if request.user.is_authenticated else None

        new_product = Product.objects.create(
            user=user,
            name=data["name"],
            description=data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

review/templates/create_review.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-6 offset-lg-3">
            <h1 class="text-center">Add New Review</h1>
            <form method="POST">
                {% csrf_token %}
                <table class="table table-bordered">
                    {{ form.as_table }}
                    <tr>
                        <td></td>
                        <td class="text-center">
                            <button type="submit" class="btn btn-primary">Add Review</button>
                        </td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
</div>
{% endblock %}

review/templates/edit_review.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<h1>Edit Review</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Edit review"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

review/templates/reviewbuku.html
{% extends 'base.html' %}
{% block content %}
    <style>
        .content {
            margin-top: 70px; /* Sesuaikan tinggi navigation bar */
        }
        
        h1 {
            text-align: center;
            margin-top: 20px;
            font-size: 36px;
            background-color: #007bff; /* Ganti warna latar belakang */
            color: #fff; /* Ganti warna font */
            padding: 10px; /* Menambahkan ruang di sekitar teks */
            border-radius: 10px; /* Membuat sudut bulat */
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        table, th, td {
            border: 1px solid #ccc;
        }

        th, td {
            padding: 12px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
            color: #333;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        tr:nth-child(odd) {
            background-color: #fff;
        }

        h5 {
            font-size: 20px;
            margin-top: 20px;
        }

        p {
            font-size: 16px;
        }

        .modal-content {
            border-radius: 10px;
        }

        .modal-header {
            background-color: #007bff;
            color: #fff;
        }

        .modal-title {
            font-size: 24px;
        }
    </style>

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Review</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="form" onsubmit="return false;">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name" class="col-form-label">Nama Buku:</label>
                            <input type="text" class="form-control" id="name" name="name">
                        </div>
                        <div class="mb-3">
                            <label for="description" class="col-form-label">Review Buku:</label>
                            <textarea class="form-control" id="description" name="description"></textarea>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Review</button>
                </div>
            </div>
        </div>
    </div>

    <h1>Review Buku</h1>

    <table id="review_table"></table>

    <script>
        async function getReview() {
            return fetch("{% url 'review_buku:get_review_json' %}").then((res) => res.json())
        }

        async function refreshReview() {
            document.getElementById("review_table").innerHTML = ""
            const reviews = await getReview()
            let htmlString = `<tr>
                <th>Nama Buku</th>
                <th>Review Buku</th>
                <th>Date Added</th>
            </tr>`
            reviews.forEach((item) => {
                htmlString += `<tr>
                <td>${item.fields.name}</td>
                <td>${item.fields.description}</td>
                <td>${item.fields.date_added}</td>
                </tr>`
            })

            document.getElementById("review_table").innerHTML = htmlString
        }

        refreshReview()

        function addReview() {
            fetch("{% url 'review_buku:add_review_ajax' %}", {
                method: "POST",
                body: new FormData(document.querySelector('#form'))
            }).then(refreshReview)

            document.getElementById("form").reset()
            return false
        }

        document.getElementById("button_add").onclick = addReview
    </script>

    <a href="{% url 'review_buku:create_review' %}">
        <button class="btn btn-primary">Add New Review</button>
    </a>

    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Review by AJAX</button>
    
{% endblock content %}