PageTurn/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('homepage.urls')),
    path('laporan_buku_rusak/', include('laporan_buku_rusak.urls')),
    path('admin/', admin.site.urls),
    path('katalog/', include('katalog.urls')),
    path('peminjaman/', include('peminjaman.urls')),
    path('review/', include('review.urls')),
    path('request_buku/', include('request_buku.urls')),
    path('auth/', include('authentication.urls')),
]

homepage/urls.py
from django.urls import path

from homepage.views import *

app_name = 'homepage'

urlpatterns = [
    path('', show_homepage, name='show_homepage'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('get_favourite_books/',get_favourite_books, name='get_favourite_books'),
]

review/urls.py
from django.urls import path

from review.views import (add_review_ajax, create_product_flutter,
                          create_review, delete_review, edit_review,
                          get_review_json, show_json, show_main)

app_name = 'review_buku'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-review', create_review, name='create_review'),
    path('edit-review/<int:id>', edit_review, name='edit_review'),
    path('delete/<int:id>', delete_review, name='delete_review'), # sesuaikan dengan nama fungsi yang dibuat
    path('get-review/', get_review_json, name='get_review_json'),
    path('create-product-ajax/', add_review_ajax, name='add_review_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
    path('json/', show_json, name='show_json'),
]

homepage/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    ROLES = [
        ('member', 'Member'),
        ('admin', 'Admin'),
    ]
    role = models.CharField(max_length=10, choices=ROLES, default='Member')

homepage/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('username', 'password1', 'password2')

homepage/views.py
import datetime
import hashlib

from django.contrib import messages
from django.contrib.auth import authenticate
from django.contrib.auth import login
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core import serializers
from django.db.models import F, Max
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from homepage.models import *
from katalog.models import Book

from .forms import CustomUserCreationForm


def get_favourite_books(request):
    # Order the books by cnt_dipinjam in descending order and select the top 5
    books_with_highest_cnt_dipinjam = Book.objects.order_by('-cnt_dipinjam')[:5]  
    # Convert the selected books to a list of dictionaries
    book_list = list(books_with_highest_cnt_dipinjam.values())
    
    return JsonResponse({'favourite_books': book_list})

def show_homepage(request):
    for item in Book.objects.filter(name = 'Judy Hopps'):
        item.delete()
    highest_cnt_dipinjam = Book.objects.aggregate(max_cnt_dipinjam=Max('cnt_dipinjam'))['max_cnt_dipinjam']
    books_with_highest_cnt_dipinjam = Book.objects.filter(cnt_dipinjam=highest_cnt_dipinjam)
    return render(request, 'homepage.html', {'favourite_books': books_with_highest_cnt_dipinjam})

def register(request):
    if request.user.is_authenticated:
        return redirect('homepage:show_homepage')
    form = CustomUserCreationForm()

    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('homepage:show_homepage')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.user.is_authenticated:
        return redirect('homepage:show_homepage')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("homepage:show_homepage")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('homepage:show_homepage'))
    response.delete_cookie('last_login')
    return response

homepage/templates/homepage.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<head>
    {% block meta %}
    <link rel="stylesheet" href="{% static 'css/homepage.css' %}?{% now "U" %}">
    {% endblock meta %}
</head>
<body>
    {% include 'header.html' %}
    <div class="background-container">
        <img src="https://uiii.ac.id/assets/images/1636690539-alfons-morales-YLSwjSy7stw-unsplash-2.jpg" alt="Background Image" class="background-image">
        <div class="background-overlay"></div>
    </div>
    <div class="right-section">
        <h2>Favourite books</h2>
        <div class="book-list">
            {% for book in favourite_books %}
            <div class="card">
                <img src="{{ book.image }}" alt="{{ book.name }} Cover">
                <h2>{{ book.name }}</h2>
                <p>Author: {{ book.author }}</p>
                <p>Rating: {{ book.rating }}</p>
                <p>Borrowed : {{ book.cnt_dipinjam }}</p>
                <p>Year: {{ book.year }}</p>
                <p>Genre: {{ book.genre }}</p>
                <a class="read-more-link" href="#">Read More</a>
                <div class="description hidden">{{ book.description }}</div>
            </div>
            {% endfor %}
        </div>
        <button id="prev-button">Previous</button>
        <button id="next-button">Next</button>
    </div>
    </div>
    <div class="content-container">
        <div class="content">
            <p style="text-align: center;">“Perpustakaan adalah rumah berteduh bagi para <span class="highlighted-text">pencari ilmu"</span>.</p>
        </div>
        <div class="product-box">
            <a href="/peminjaman/">Mulai Pinjam Buku</a>
        </div>
    </div>

</body>

<script src="{% static 'js/homepage.js' %}?{% now "U" %}"></script>


{% endblock content %}

homepage/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}?{% now "U" %}">
{% endblock meta %}

{% block header %}
{% endblock header %}

{% block content %}

<body style="background-color: #282626;">
    <div class="title" style="margin-top: 100px">Login</div>   
    <div class="login-container">
        <form method="POST" action="{% url 'homepage:login' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" id="username" name="username" placeholder="Enter your username">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" id="password" name="password" placeholder="Enter your password">
            </div>
            <div class="form-group">
                <button type="submit">Login</button>
            </div>
        </form>
        <div class="register-link">
            Don't have an account? <a href="{% url 'homepage:register' %}" style="color: white; text-decoration: underline;">Register</a>
        </div>
        {% if messages %}
        <div class="login-failed">
            <ul>
                {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

</div>

{% endblock content %}

{% block footer %}
{% endblock footer %}

homepage/templates/register.html
{% extends 'base.html' %}

{% load static %}
{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block header %}
{% endblock header %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/register.css' %}?{% now "U" %}">
<body>
    <div class="title">Register</div>
    <div class="login-container">
        <form method="post" action="{% url 'homepage:register' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="form-group">
                <button>Register</button>
            </div>
        </form>
    </div>
</body>
</html>


{% endblock content %}

{% block footer %}
{% endblock footer %}