PageTurn/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('homepage.urls')),
    path('laporan_buku_rusak/', include('laporan_buku_rusak.urls')),
    path('admin/', admin.site.urls),
    path('katalog/', include('katalog.urls')),
    path('peminjaman/', include('peminjaman.urls')),
    path('review/', include('review.urls')),
    path('request_buku/', include('request_buku.urls')),
    path('auth/', include('authentication.urls')),
]

katalog/urls.py
from django.contrib import admin
from django.urls import include, path

from katalog.views import *

app_name = "katalog"

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
    path('get-book/', get_book_json, name='get_book_json'),
    path('create-book-ajax/', add_book_ajax, name='add_book_ajax'),
    path('get-genres/', get_genre_json, name='get_genre_json'),
    path('get-books-genre/', get_books_by_genre, name='get-books-by-genre'),
    path('create-flutter/', create_flutter, name='create_flutter'),
]

review/urls.py
from django.urls import path

from review.views import (add_review_ajax, create_product_flutter,
                          create_review, delete_review, edit_review,
                          get_review_json, show_json, show_main)

app_name = 'review_buku'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-review', create_review, name='create_review'),
    path('edit-review/<int:id>', edit_review, name='edit_review'),
    path('delete/<int:id>', delete_review, name='delete_review'), # sesuaikan dengan nama fungsi yang dibuat
    path('get-review/', get_review_json, name='get_review_json'),
    path('create-product-ajax/', add_review_ajax, name='add_review_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
    path('json/', show_json, name='show_json'),
]

katalog/models.py
from django.db import models

# Create your models here.
# Name, Author,User Rating,Reviews,Price,Year,Genre, image, description

class Book(models.Model):
    name = models.CharField(max_length=255, null=True, blank=True)
    author = models.CharField(max_length=255, null=True, blank=True)
    rating =  models.FloatField(null=True, blank=True, default=0)
    review =   models.IntegerField(null=True, blank=True, default=0)
    price = models.IntegerField(null=True, blank=True)
    year = models.IntegerField(null=True, blank=True)
    genre = models.CharField(max_length=255, null=True, blank=True)
    image = models.CharField(max_length=255, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    is_dipinjam = models.BooleanField(default=False)
    cnt_dipinjam = models.IntegerField(default=0)
    

katalog/forms.py
from django import forms
from .models import Book

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['name', 'author', 'rating', 'review', 'price', 'year', 'genre', 'image', 'description']

katalog/views.py
import json

from django.core import serializers
from django.http import HttpResponse, HttpResponseNotFound, JsonResponse
from django.shortcuts import redirect, render
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods

from katalog.models import Book

from .forms import BookForm


def get_books(request):
    data = Book.objects.all()
    return HttpResponse(serializers.serialize("json", data),
    content_type = "application/json")

def show_katalog(request):
    book = Book.objects.all()
    
    context = {
        'book': book,
    }

    return render(request, "katalog.html", context)

def get_book_json(request):
    book_item = Book.objects.all()
    return HttpResponse(serializers.serialize('json', book_item))

def get_books_by_genre(request):
    search_query = request.GET.get('search', '')
    genres = request.GET.getlist('genres')
    if genres:
        books = Book.objects.filter(genre__in=genres)
    else:
        books = Book.objects.all()
    books_ret = []
    for book in books:
        if search_query.lower() in book.name.lower() or search_query.lower() in book.author.lower():
            books_ret.append(book)
    # Serialisasi data buku ke JSON
    return HttpResponse(serializers.serialize('json', books_ret))

def get_genre_json(request):
    book_item = Book.objects.all()
    tmp = set()
    for x in book_item:
        tmp.add(x.genre)
    genres = []
    for x in tmp:
        genres.append(x)
    return JsonResponse({'genres': genres})

@csrf_exempt
def add_book_ajax(request):
    if request.method == 'POST':
        form = BookForm(request.POST)
        if form.is_valid():
            form.save()
            return JsonResponse({"status": "CREATED"}, status=201)
        else:
            return JsonResponse({"status": "error", "FORM NOT VALID": form.errors}, status=400)
    return JsonResponse({"status": "error"}, status=400)

@csrf_exempt
def create_flutter(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        Book.objects.create(
            name=data['name'],
            author=data['author'],
            year=data['year'],
            rating=data['rating'],
            review=data['review'],
            price=data['price'],
            genre=data['genre'],
            image=data['image'],
            description=data['description'],
            is_dipinjam = False,
            cnt_dipinjam = 0,
        )
        return JsonResponse({"status": "success"}, status=200)
    return JsonResponse({"status": "error"}, status=401)

katalog/templates/katalog.html
{% extends 'base.html' %}

{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        :root {
            --surface-color: #fff;
            --curve: 40;
        }

        * {
            box-sizing: border-box;
        }

        body {
            font-family: "Noto Sans JP", sans-serif;
            background-color: #fef8f8;
        }

        .cards {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(400px, 1fr));
            gap: 2rem;
            margin: 4rem 5vw;
            padding: 0;
            list-style-type: none;
        }

        .card {
            position: relative;
            display: block;
            width: 400px;
            height: 600px;
            border-radius: calc(var(--curve) * 1px);
            overflow: hidden;
            text-decoration: none;
            /* margin: 0 150px; */
        }

        .card__image {
            width: 100%;
            height: auto;
        }

        .card__overlay {
            position: absolute;
            bottom: 0;
            left: 0;
            right: 0;
            z-index: 1;
            border-radius: calc(var(--curve) * 1px);
            background-color: var(--surface-color);
            transform: translateY(100%);
            transition: 0.2s ease-in-out;
        }

        .card__overlay::-webkit-scrollbar {
            width: 10px; /* Adjust scrollbar width as needed */
        }

        .card__overlay::-webkit-scrollbar-track {
            border-radius: 10px; /* Rounded corners for the track */
        }

        .card:hover .card__overlay {
            transform: translateY(0);
            overflow-y: auto; /* Make the overlay scrollable */
        }

        .card__header {
            position: relative;
            display: flex;
            align-items: center;
            gap: 2em;
            padding: 2em;
            border-radius: calc(var(--curve) * 1px);
            background-color: var(--surface-color);
            transform: translateY(-100%);
            transition: 0.2s ease-in-out;
        }

        .card__arc {
            width: 80px;
            height: 80px;
            position: absolute;
            bottom: 100%;
            right: 0;
            z-index: 1;
        }

        .card:hover .card__header {
            transform: translateY(0);
        }

        .card__title {
            font-size: 1em;
            margin: 0;
            color: #6a515e;
            margin: 0 0 0.3em;
            color: #6a515e;
            overflow: hidden;
            display: -webkit-box;
            -webkit-box-orient: vertical;
            -webkit-line-clamp: 3;

        }

        .card__tagline {
            display: block;
            margin: 1em 0;
            font-family: "MockFlowFont";
            font-size: 0.8em;
            color: #d7bdca;
        }

        .card__status {
            font-size: 0.8em;
            color: #d7bdca;
        }

        .card__description {
            padding: 0 2em;
            margin: 0;
            color: #d7bdca;
            font-family: "MockFlowFont";
            display: -webkit-box;
            -webkit-box-orient: vertical;
            -webkit-line-clamp: 3;
        }
    </style>
</head>

<body>

<div class="container mt-5" style="padding-bottom: 30px;">
    <div class="row mt-4">
        <div class="col-md-6">
            {% if request.user.role == "admin" %}
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addBookModal">Add Book</button>
            {% endif %}
        </div>
    </div>
</div>

<!-- Add Book Modal -->
<div class="modal fade" id="addBookModal" tabindex="-1" role="dialog" aria-labelledby="addBookModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addBookModalLabel">Add Book</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </button>
            </div>
            <div class="modal-body">
                <form id="form" onsubmit="return false;">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="name">Name:</label>
                        <input type="text" class="form-control" id="name" name="name" required>
                    </div>
                    <div class="form-group">
                        <label for="author">Author:</label>
                        <input type="text" class="form-control" id="author" name="author" required>
                    </div>
                    <div class="form-group">
                        <label for="rating">User Rating:</label>
                        <input type="number" step="0.1" class="form-control" id="rating" name="rating" required>
                    </div>
                    <div class="form-group">
                        <label for="review">Reviews:</label>
                        <input type="number" class="form-control" id="review" name="review" required>
                    </div>
                    <div class="form-group">
                        <label for="price">Price:</label>
                        <input type="number" class="form-control" id="price" name="price" required>
                    </div>
                    <div class="form-group">
                        <label for="year">Year:</label>
                        <input type="number" class="form-control" id="year" name="year" required>
                    </div>
                    <div class="form-group">
                        <label for="genre">Genre:</label>
                        <input type="text" class="form-control" id="genre" name="genre" required>
                    </div>
                    <div class="form-group">
                        <label for="image">Image URL:</label>
                        <input type="text" class="form-control" id="image" name="image" required>
                    </div>
                    <div class="form-group">
                        <label for="description">Description:</label>
                        <textarea class="form-control" id="description" name="description" rows="4" required></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Book</button>
            </div>
        </div>
    </div>
</div>

<div class="row" id="book_table">
</div>

<script>
    async function getBooks() {
        return fetch("{% url 'katalog:get_book_json' %}").then((res) => res.json());
    }

    async function refreshBooks() {
        document.getElementById("book_table").innerHTML = "";
        const books = await getBooks();
        let htmlString = `
    <div class="row">
        <div class="text-center">
            <h1><b> Setiap halaman berisi petualangan yang menunggu untuk ditemukan. </b></h1>
            <h2> Segera  jelajahi ${books.length} pilihan buku dalam koleksi kami! </h2>
        </div>
    </div>

    <ul class="cards">`;  // Open the <ul> for the cards

    books.forEach((item) => {
        htmlString += `
            <li>
                <a href="/peminjaman/new/#${item.pk}" class="card">
                    <img src="${item.fields.image}" class="card__image" alt="" />
                    <div class="card__overlay">
                        <div class="card__header">
                            <svg class="card__arc"</svg>
                            <div class="card__header-text">
                                <h3 class="card__title">${item.fields.name}</h3>
                                <span class="card__status">${item.fields.author}</span>
                            </div>
                        </div>
                        <table>
                            <tr>
                                <td><p class="card__description">Year: ${item.fields.year}</p></td>
                            </tr>

                            <tr>
                                <td><p class="card__description">Genre: ${item.fields.genre}</p></td>
                            </tr>   

                            <tr>
                                <td><p class="card__description">User Rating: ${item.fields.rating}⭐ (${item.fields.review}) </p></td>
                            </tr>
                            <tr>
                                <td><p class="card__description">${item.fields.description}</p></td>
                            </tr>
                        </table>
                    </div>
                </a>
            </li>`;  // Add each book card as an <li> within the <ul>
    });

    htmlString += `
        </ul>
        `;

    document.getElementById("book_table").innerHTML = htmlString;

    }

    refreshBooks();

    function addBook() {
        fetch("{% url 'katalog:add_book_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        })
        .then(refreshBooks)
        .catch(error => console.error('Error adding book:', error));

        document.getElementById("form").reset();
        return false;
    }

    document.getElementById("button_add").onclick = addBook;
</script>

</body>
</html>
{% endblock content %}